### ISSUE TITLE
How to use built primitive type serialization instead of writing wrapper types for every possible value

### ISSUE THREAD

**Issue by tedbarth** [Cysharp/MemoryPack#225] opened 2024-02-10 08:59 UTC
Deep in many of my static networked data types (all implement my own ISerializable) I have the following type.
```c#
public partial class NetworkVariableData : ISerializable {
  public readonly ushort Index;
  public readonly ISerializable? Value;
}
```
`Value` here can be almost anything (I write a library, so it is up to the user of the library). Of course I want to support as many types as possible. Right now I have Implemted `ISerializable` as union:

```c#
[MemoryPackable(GenerateType.NoGenerate)]
public partial interface ISerializable {
  // Just a marker
}
```

```c#
    (ushort, Type t)[] types = AppDomain.CurrentDomain.GetAssemblies()
      .SelectMany(a => a.ExportedTypes)
      .Where(t => t.GetInterfaces().Contains(typeof(ISerializable)) && !t.IsAbstract)
      .Select((t, i) => ((ushort)i, t))
      .ToArray();

    var formatter = new DynamicUnionFormatter<ISerializable>(types);

    MemoryPackFormatterProvider.Register(formatter);
```

This works fine, but I still have to write basic wrapper type for every known types, which already is becoming tedious, inflexible and error prone.

Example of how I would convert to `ISerializable`:
```c#
public static ISerializable? ToSerializable(object? value) {
    switch (value) {
      case null:
        return null;
      case ISerializable serializable:
        return serializable;
      default: {
        var type = value.GetType();
        return value switch {
          double v => new DoubleData(v),
          short v => new ShortData(v),
          ushort v => new UnsignedShortData(v),
          int v => new IntData(v),
          bool v => new BoolData(v),
          string v => new StringData(v),
          // Oh god, there are so many! :'(
          _ => throw new UnreachableException($"Cannot serialize type '{type}'")
        };
      }
    }
  }
```
Example of a wrapper `ISerializable`:
```c#
[MemoryPackable]
public partial class ShortData : ISerializable {
  [MemoryPackInclude] public readonly short? Value;

  public ShortData(short? value) {
    Value = value;
  }
}
```

**MemoryPack** already supports many standard types (at least the primitives). How can I make use of those without having to write those wrapper types?

**Comment by tedbarth** [comment] 2024-02-11 09:50
@neuecc **Proposal:** Add API to get an index (or id) of a formatter and a formatter by index (or id):
```C#
  public class UnknownObjectFormatter : MemoryPackFormatter<Object?> {
    public override void Serialize<TBufferWriter>(
      ref MemoryPackWriter<TBufferWriter> writer,
      scoped ref Object? value) {
      if (value == null) {
        writer.WriteNullObjectHeader();
        return;
      }

      Type type = value.GetType();
      ushort index = MemoryPackFormatterProvider.GetFormatterIndex(type);
      var formatter = MemoryPackFormatterProvider.GetFormatter(type);

      writer.WriteValue(index);
      formatter.Serialize(writer, value);
    }

    public override void Deserialize(ref MemoryPackReader reader, scoped ref Object? value) {
      if (!reader.TryReadObjectHeader(out var count)) {
        value = null;
        return;
      }

      ushort index = reader.ReadValue<ushort>();
      var formatter = MemoryPackFormatterProvider.GetFormatterByIndex();

      value = formatter.Deserialize(reader);
    }
  }
  ```
It is slower than when using static types, but not that much. I would expect it to be much faster that when having to wrap _every_ value into an object on the heap. And there is no need to write boiler plate wrapper classes for primitives.

**Comment by tedbarth** [comment] 2024-02-12 09:06
I helped myself with the following formatter:
```
public class KnownObjectFormatter : MemoryPackFormatter<Object?> {
    public class KnownObjectFormatterException(string message) : Exception(message);
    private static readonly Bictionary<Type, ushort> RegisteredTypes = new Bictionary<Type, ushort>();

    public static void RegisterType(Type type) {
      if (!RegisteredTypes.ContainsKeyForward(type)) {
        ushort index = (ushort)RegisteredTypes.Count;
        RegisteredTypes.Add(type, index);
      }
    }

    public override void Serialize<TBufferWriter>(
      ref MemoryPackWriter<TBufferWriter> writer,
      scoped ref Object? value) {
      if (value == null) {
        writer.WriteNullObjectHeader();
        return;
      }

      Type type = value.GetType();

      if (!RegisteredTypes.TryGetValueForward(type, out ushort index)) {
        throw new KnownObjectFormatterException($"Type {type} not registered");
      }
      var formatter = writer.GetFormatter(type);

      writer.WriteValue<ushort>(index);
      formatter.Serialize(ref writer, ref value);
    }

    public override void Deserialize(ref MemoryPackReader reader, scoped ref Object? value) {
      if (!reader.TryReadObjectHeader(out var count)) {
        value = null;
        return;
      }

      ushort index = reader.ReadValue<ushort>();
      if (!RegisteredTypes.TryGetValueReverse(index, out var type)) {
        throw new KnownObjectFormatterException($"No type with index {index} registered");
      }
      var formatter = reader.GetFormatter(type!);

      formatter.Deserialize(ref reader, ref value);
    }
  }
  
  public class KnownObjectFormatterAttribute : MemoryPackCustomFormatterAttribute<object?> {
    private static readonly KnownObjectFormatter Formatter = new KnownObjectFormatter();

    public override IMemoryPackFormatter<object?> GetFormatter() {
      return Formatter;
    }
  }
```

That boils down to usage:
```
KnownObjectFormatter.RegisterType(typeof(int));
KnownObjectFormatter.RegisterType(typeof(int?));
KnownObjectFormatter.RegisterType(typeof(int[]));
KnownObjectFormatter.RegisterType(typeof(bool));
KnownObjectFormatter.RegisterType(typeof(bool?));
KnownObjectFormatter.RegisterType(typeof(bool[]));
KnownObjectFormatter.RegisterType(typeof(string));
KnownObjectFormatter.RegisterType(typeof(string[]));
...
KnownObjectFormatter.RegisterType(typeof(MyCustomType));
KnownObjectFormatter.RegisterType(typeof(MyCustomType?));
KnownObjectFormatter.RegisterType(typeof(MyCustomType[]));
...
```

It still would be tedious to do that for every possible type, but it at least is better than having to write wrapper classes.

**Anyway**, I have the problem with the above code:
The serialization of the `index` (at least) is broken. For example, I serialize a type **A** with index **6**. And when the formatter tries to deserialize that, it reads out index **63744** instead of **6**. Any idea if there is something wrong with my formatter?

**Comment by hadashiA** [comment] 2024-03-14 01:35
Hello.
This issue is probably a duplicate of #186.
Unfortunately, dynamically inferring types is difficult due to the binary spec.

We have looked at your KnownObjectFormatter and would like to recommend using Union for official support. The above sample should be substitutable with Union.

**Closed by hadashiA** 2024-03-14 01:35 UTC
